import { Manrope, JetBrains_Mono } from "next/font/google";
import "@/styles/elements.scss";

const ManropeFont = Manrope({
  variable: "--font-manrope",
  subsets: ["latin", "cyrillic"],
  display: "swap",
  weight: ["400", "500", "600", "700"]
});

const JetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin", "cyrillic"],
  display: "swap",
  weight: ["400", "500", "600", "700"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${ManropeFont.variable} ${JetBrainsMono.variable}`}>
        {children}
      </body>
    </html>
  );
}